#服务端：
server:
  port: 80
  servlet:
    context-path: /tree

tree:
  domain: http://120.79.217.47/


#数据源：
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.79.217.47:3306/tree?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/tree?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ding1230@
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
 #     initial-size: 5
  #    min-idle: 5
   #   max-active: 20
    #  max-wait: 60000



fdfs:
  connect-timeout: 3000
  so-timeout: 3000
  tracker-list: 120.79.217.47:22122
  web-server-url: http://120.79.217.47/
#mybatis
mybatis:
  type-aliases-package: com.stone.tree.web.*.bean # 所有Entity别名类所在包
  config-location: classpath:mybatis/mybatis-config.xml # mybatis配置文件所在路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件

#pageHelper
pagehelper:
  #dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#sql日志：
logging:
  level:
    com:
      stone:
        tree:
          web: debug



